### ISSUE TITLE
Can you add `share=True` CLI argument to enable running this on Colab?

### ISSUE THREAD

**Issue by amrrs** [abhishekkrthakur/diffuzers#1]
demo.launch(share = True) enables running this app on Colab. Is it possible to add that as a CLI argument?

**Comment by abhishekkrthakur** [comment]
added to the cli. please note that `model_path` has changed to `model`. run with share enabled using:

```
diffuzers run --model stabilityai/stable-diffusion-2-1 --output_path ~/path_to_save_output/ --share
```

**Comment by amrrs** [comment]
Thanks. Will check it tomorrow 🙏🏽

**Comment by amrrs** [comment]
My bad I thought this is Gradio and raised this.

**Comment by abhishekkrthakur** [comment]
it was when you created the issue :)

**Comment by abhishekkrthakur** [comment]
fyi: latest version has colab support
