### ISSUE TITLE
What is the expected format for and img2img request?

### ISSUE THREAD

**Issue by J3rr1ck** [abhishekkrthakur/diffuzers#13]
Hey all trying to play with the api and assumed that it wanted a base 64 image for the img2img post request but that seems not to be the case? can anyone point me in the right direction?

**Comment by abhishekkrthakur** [comment]
its multipart/form-data. e.g curl request:

```
curl -X 'POST' \
  'http://127.0.0.1:8000/img2img?prompt=test&negative_prompt=negative%20test&scheduler=EulerAncestralDiscreteScheduler&strength=0.7&num_images=1&guidance_scale=7&steps=50&seed=42' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'image=@image.png;type=image/png'
```

you can also take a look at api docs and try the api on: `host:port/docs`

**Comment by J3rr1ck** [comment]
tysm for the super fast response
