### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by authorai** [abhishekkrthakur/diffuzers#14]
Ran in venv, followed instructions to run `diffuzers app`

**Error**
```
python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
```

**Hardware**
MacBook Pro (13-inch, 2020
16 GB 3733 MHz LPDDR4X
Intel Iris Plus Graphics 1536 MB
2 GHz Quad-Core Intel Core i5

**Comment by abhishekkrthakur** [comment]
which model gives you this error?

**Comment by abhishekkrthakur** [comment]
fixed in latest version

**Comment by authorai** [comment]
thank you!
