### ISSUE TITLE
pix2pix

### ISSUE THREAD

**Issue by J3rr1ck** [abhishekkrthakur/diffuzers#19]
hey all just checking if pix2pix is supposed to be working as I'm getting some odd errors
`ValueError: Incorrect configuration settings! The config of `pipeline.unet`: FrozenDict([('sample_size', 64), ('in_channels', 4), ('out_channels', 4), ('center_input_sample', False), ('flip_sin_to_cos', True), ('freq_shift', 0), ('down_block_types', ['CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'CrossAttnDownBlock2D', 'DownBlock2D']), ('mid_block_type', 'UNetMidBlock2DCrossAttn'), ('up_block_types', ['UpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D', 'CrossAttnUpBlock2D']), ('only_cross_attention', False), ('block_out_channels', [320, 640, 1280, 1280]), ('layers_per_block', 2), ('downsample_padding', 1), ('mid_block_scale_factor', 1), ('act_fn', 'silu'), ('norm_num_groups', 32), ('norm_eps', 1e-05), ('cross_attention_dim', 1024), ('attention_head_dim', [5, 10, 20, 20]), ('dual_cross_attention', False), ('use_linear_projection', True), ('class_embed_type', None), ('num_class_embeds', None), ('upcast_attention', False), ('resnet_time_scale_shift', 'default'), ('_class_name', 'UNet2DConditionModel'), ('_diffusers_version', '0.8.0'), ('_name_or_path', '/home/jerrick/.cache/huggingface/diffusers/models--stabilityai--stable-diffusion-2-base/snapshots/d28fc8045793886e512c5389771d3b3d560f9575/unet')]) expects 4 but received `num_channels_latents`: 4 + `num_channels_image`: 4  = 8. Please verify the config of `pipeline.unet` or your `image` input.
`

**Comment by J3rr1ck** [comment]
figured it out

**Comment by hamin** [comment]
@J3rr1ck I'm running into the same issue. Any pointers?

**Comment by J3rr1ck** [comment]
The diffusers pix2pix-sd model [here](https://huggingface.co/diffusers/pix2pix-sd) is the only model I've gotten working so far

**Comment by abhishekkrthakur** [comment]
yeah. it needs to be a pix2pix model.

**Comment by abhishekkrthakur** [comment]
this will also work: https://huggingface.co/timbrooks/instruct-pix2pix

**Comment by J3rr1ck** [comment]
I get the following error with the timbrooks model 
`> ERROR   Model type not supported, img2img pipeline not created`

**Comment by abhishekkrthakur** [comment]
reopening. will take a look. it should work.

**Comment by J3rr1ck** [comment]
Any luck on poking this? Any way others can help?
