### ISSUE TITLE
Intended audience - everyone?

### ISSUE THREAD

**Issue by aolko** [abhishekkrthakur/diffuzers#6]
Can you simplify `diffuzers` so it meets the desired intended audience of `everyone`? Or at least, spin a new version made for `everyone` from the ground up?

**Comment by abhishekkrthakur** [comment]
appreciate your feedback. please explain a bit more so that i can help :)

**Comment by abhishekkrthakur** [comment]
Thank you! I'll try to make it more user-friendly. However, the advanced features and options must be kept for advanced users :)

**Comment by aolko** [comment]
> Thank you! I'll try to make it more user-friendly. However, the advanced features and options must be kept for advanced users :)

Nah, advanced users already have AUTOMATIC1111 UI

**Comment by aolko** [comment]
Oh and can you give an ETA? Just so I know if I should wait for it or no.

**Comment by abhishekkrthakur** [comment]
No ETA. ill just add help texts to make it easier for non tech audience to understand. I have no intention of removing features and will keep support for advanced users.

**Comment by aolko** [comment]
So essentially you are opting for a half-measure here even though more drastic changes are needed. Well, that sucks.

**Comment by abhishekkrthakur** [comment]
I apologize, I might not have understood your concern. If you believe that drastic changes are needed to make it user friendly, please put concrete suggestions to help me understand better. Maybe in form of a simple screenshot?

**Comment by aolko** [comment]
> I apologize, I might not have understood your concern. If you believe that drastic changes are needed to make it user friendly, please put concrete suggestions to help me understand better. Maybe in form of a simple screenshot?

I think [I have posted a list](https://github.com/abhishekkrthakur/diffuzers/issues/6#issuecomment-1378526089). 

If I'm going to get more involved, I'd rather attempt to DIY, however, knowing how 🤗 treats `transformers` with [the whole "this is not a modular toolbox" approach](https://github.com/huggingface/transformers#why-shouldnt-i-use-transformers:~:text=This%20library%20is%20not%20a%20modular%20toolbox%20of%20building%20blocks%20for%20neural%20nets.%20The%20code%20in%20the%20model%20files%20is%20not%20refactored%20with%20additional%20abstractions%20on%20purpose%2C%20so%20that%20researchers%20can%20quickly%20iterate%20on%20each%20of%20the%20models%20without%20diving%20into%20additional%20abstractions/files.), I'd need exactly that, since [I'm not a data scientist, yo](https://imgix.ranker.com/list_img_v2/9660/549660/original/very-best-of-the-i-have-no-idea-what-i-m-doing-meme-u1?w=817&h=427&fm=jpg&q=50&fit=crop).

**Comment by abhishekkrthakur** [comment]
Got it! Will add some improvements this weekend. Lets see if thats what you mean. :)

**Comment by aolko** [comment]
> Got it! Will add some improvements this weekend. Lets see if thats what you mean. :)

I don't see any improvements

**Comment by aolko** [comment]
> this is a part time thing i do and not as my main priority. please dont hold your breath.

you are responsible for your own ETAs, keep that responsibility

**Comment by abhishekkrthakur** [comment]
OS owners dont owe anyone anything and neigther do i. License is permissive so make your own fork and your own changes if you are in a hurry. else learn to wait or ask properly. im done here. a part of this has been done. nothing more will be taken up by me. feel free to fork and make your own changes or use any other tool.
