### ISSUE TITLE
Conda env doesn't seem to be respected

### ISSUE THREAD

**Issue by cian0** [abhishekkrthakur/diffuzers#7]
Each time I run it with a new conda env, it always say all the dependencies/modules that were installed are not found

It is fixed when I move out of the env and do a pip install -r requirements.txt (not ideal as I have other apps conflicting)

Error happens when I run ```diffuzers api```

**Comment by abhishekkrthakur** [comment]
thank you for reporting. fixed in v 0.2.5

**Comment by cian0** [comment]
confirmed! thanks!
